# Generated by Django 4.1.7 on 2023-03-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_album_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='releaseDate',
            field=models.DateField(null=True),
        ),
    ]
