# Generated by Django 4.1.7 on 2023-03-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_record_releasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='artist',
        ),
        migrations.AddField(
            model_name='record',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.band'),
            preserve_default=False,
        ),
    ]
