# Generated by Django 4.1.7 on 2023-03-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_band_remove_record_artist_record_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
