# Generated by Django 4.1.7 on 2023-03-31 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_record_tracklist_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='record',
        ),
    ]
