# Generated by Django 4.1.7 on 2023-04-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_album_song_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='genre',
        ),
        migrations.AddField(
            model_name='record',
            name='genre',
            field=models.ManyToManyField(to='main_app.genre'),
        ),
    ]
