# Generated by Django 4.1.7 on 2023-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_genre_remove_record_genre_record_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=250)),
                ('bio', models.TextField(max_length=500)),
                ('instrument', models.ManyToManyField(to='main_app.instrument')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='artists',
            field=models.ManyToManyField(to='main_app.artist'),
        ),
    ]
