# Generated by Django 4.1.7 on 2023-04-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_instrument_artist_band_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='instrument',
            new_name='instruments',
        ),
    ]
